name: Deploy
on: 
    push:
        branches: [main]

jobs:
    api_production_deployment:
        uses: ./.github/workflows/job-api.yml
        secrets: 
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

            